export const SUPPORTED_LANGUAGES = [
  "bash",
  "c",
  "cpp",
  "csharp",
  "css",
  "dart",
  "elixir",
  "go",
  "haskell",
  "hcl",
  "html",
  "java",
  "javascript",
  "json",
  "kotlin",
  "lua",
  "markdown",
  "nix",
  "php",
  "python",
  "ruby",
  "rust",
  "scala",
  "solidity",
  "swift",
  "typescript",
  "tsx",
  "yaml",
] as const;

export type SupportedLanguage = (typeof SUPPORTED_LANGUAGES)[number];

const CLI_LANGUAGE_NAMES: Readonly<Record<SupportedLanguage, string>> = {
  bash: "Bash",
  c: "C",
  cpp: "Cpp",
  csharp: "CSharp",
  css: "Css",
  dart: "Dart",
  elixir: "Elixir",
  go: "Go",
  haskell: "Haskell",
  hcl: "Hcl",
  html: "Html",
  java: "Java",
  javascript: "JavaScript",
  json: "Json",
  kotlin: "Kotlin",
  lua: "Lua",
  markdown: "Markdown",
  nix: "Nix",
  php: "Php",
  python: "Python",
  ruby: "Ruby",
  rust: "Rust",
  scala: "Scala",
  solidity: "Solidity",
  swift: "Swift",
  typescript: "TypeScript",
  tsx: "Tsx",
  yaml: "Yaml",
};

export function cliLanguageName(language: SupportedLanguage): string {
  return CLI_LANGUAGE_NAMES[language];
}
